### ISSUE TITLE
UDP Receive Buffer Size

### ISSUE THREAD

**Issue by lvnilesh** [Erisa/cloudflared-docker#12]
I see this notice in the logs:

```
my-tunnel:  failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```

The link recommends:

```
sysctl -w net.core.rmem_max=2500000
```

Does it make sense to incorporate this in your Dockerfile?

**Comment by Erisa** [comment]
That is a kernel option and cannot be changed per-container or at all from within a container without making it privileged (A bad idea)
Even if it was ran within a privileged container, it would affect the entire system which may be undesirable behaviour.

Basically that command only works on the host and you should run it on your host if you want/need it to be done.
