### ISSUE TITLE
For DoH, need to add --address 0.0.0.0, in order for resolver to accept and listen for DNS requests from LAN subnets

### ISSUE THREAD

**Issue by specterz** [Erisa/cloudflared-docker#21]
For DoH, need to add --address 0.0.0.0, in order for resolver to accept and listen for DNS requests from LAN subnets. Took a while to figure it out... maybe good to add this argument.

[https://github.com/cloudflare/cloudflared/issues/6#issuecomment-379165518](url)

**Comment by Erisa** [comment]
Thanks!
